version: "3"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./project-dev-way-api
    container_name: project-dev-way-api
    command: yarn start:prod
    restart: unless-stopped
    ports:
      - "4000:4000"
      - "9229:9229"
    environment:
      - PORT=4000



