version: "3"

services:
  # dashboard:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./project-dev-way-dashboard
  #   container_name: project-dev-way-dashboard
  #   ports:
  #     - "3020:3020"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - apiBaseUrl=http://localhost:4000
  #     - PORT=3020
  #   restart: unless-stopped
  #   command: serve -s build -l 3020

  auth:
    build:
      dockerfile: Dockerfile
      context: ./project-dev-way-auth
    container_name: project-dev-way-auth
    restart: unless-stopped
    ports:
      - "5000:5000"
    # environment:
    #   - PORT=5000
    #   - DB_HOST=auth_db
    #   - DB_PORT=5432
    #   - DB_NAME=project-dev-way-auth-db
    #   - DB_USERNAME=postgres
    #   - DB_PASSWORD=postgres
    command: >
      sh -c "npm run db:init && npm run start:prod"
    depends_on:
      - auth_db

  api:
    build:
      dockerfile: Dockerfile
      context: ./project-dev-way-api
    container_name: project-dev-way-api
    restart: unless-stopped
    ports:
      - "4000:4000"
    # environment:
    #   - PORT=4000
    #   - DB_HOST=auth_db
    #   - DB_PORT=5432
    #   - DB_NAME=project-dev-way-auth-db
    #   - DB_USERNAME=postgres
    #   - DB_PASSWORD=postgres
    command: >
      sh -c "npm run db:init && npm run start:prod"
    depends_on:
      - api_db

  auth_db:
    image: postgres:latest
    container_name: project-dev-way-auth-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project-dev-way-auth-db
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  api_db:
    image: postgres:latest
    container_name: project-dev-way-api-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project-dev-way-api-db
    volumes:
      - postgres_api_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  postgres_auth_data:
  postgres_api_data:
