version: "3"

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./project-dev-way-api
    command: yarn start:dev
    volumes:
      - /app/node_modules
      - ./project-dev-way-api/src:/app/src
